---
title: "Repeatability script"
author: "Erik Waskiewicz"
date: "24/05/2018"
output: pdf_document
header-includes: 
  - \usepackage{rotating}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)

# Create directory for study
# copy repeatability script and settings script into new folder
# copy raw data into folder and ensure filepaths match
# open settings file and follow instructions
# once setting have been checked, save file and click knit
```

```{r results='hide'}
source('repeatability_settings.R')

# Dont edit from here onwards!
######################################################################
```

# Summary  
```{r results='asis'}
cat('  \n## Parameters - ', settings_summary_count(study_parameters), '  \n')
settings_summary_list(study_parameters)

cat('  \n## Assessors - ', settings_summary_count(study_assessors), '  \n')
settings_summary_list(study_assessors)

cat('  \n## Number of sessions - ', settings_summary_count(study_sessions), '  \n')

```


```{r results='hide'}
input_list <- vector('list', length(study_sides))
i=1
for (data in study_sides) {
  # load headers and data seperately
  temp_headers <- load_headers(data[2])
  temp_data <- load_data(data[2])
  temp_data$mean <- rowMeans(temp_data)
  # combine and sort data
  temp_sorted <- sort_data(temp_data, temp_headers)
  input_list[[i]] <- temp_sorted
  i=i+1
}
# concatenate dataframes in list
sorted_data <- do.call('rbind', input_list)
write.csv(sorted_data, 'results/all_data_sorted.csv')
# clean up
rm(temp_headers, temp_data, temp_sorted, data, input_list, i)
```


```{r results='asis', fig.width=9, fig.height=12}
# create empty gait reliability profile df
grp_df <- create_grp_df()
for (parameter in study_parameters){
  # format pdf
  cat('\n\\pagebreak\n')
  cat('  \n##', parameter[1], '  \n###All trials', '  \n')
  # subset by side
  temp_side_list <- vector('list', length(study_sides))
  i=1
  for (side in study_sides){
    temp_parameter <- paste(side[1], parameter[2], sep = ' ')
    # subset total data by joint and axis
    temp_df <- split_by_joint(sorted_data, temp_parameter, parameter[3])
    temp_output <- dcast(temp_df, Session.assessor+Session.number+unique_id~variable, value.var = 'value')
    write.csv(temp_output, paste('results/', side[1], '_', parameter[1], '_df_all.csv', sep = ''))
    # Loop through sessions
    temp_session_list <- vector('list', length(study_sessions))
    j=1
    for (study in study_sessions) {
      # subset data
      temp_subset <- subset(temp_df, Session.number == study[1] & variable != 'mean')
      # plot graph
      temp_plot <- plot_graph_all(temp_subset, paste(study[1], side[1], sep = ' - '), parameter[1], parameter[4], parameter[5], parameter[6])
      temp_leg <- get_legend(temp_plot)
      temp_plot <- temp_plot + theme(legend.position = 'none')
      temp_session_list[[j]] <- temp_plot
      # clean up
      rm(temp_subset, temp_plot)
      j=j+1
    }
    temp_side_list[[i]] <- temp_session_list
    rm(study, j)
    i=i+1
  }
  rm(side, i)
  # combine left and right plots, display plot and save
  temp_plot <- combine_plots(temp_side_list, temp_leg)
  plot(temp_plot)
  temp_name <- paste('results/', parameter[1], '_plot_all.png', sep = '')
  save_plot(temp_name, temp_plot, base_height = 15, base_width = 12)
  # clean up
  rm(temp_df, temp_plot, temp_session_list, temp_side_list, temp_parameter, temp_leg, temp_name)

################
  
  # format pdf
  cat('\n\\pagebreak\n')
  cat('  \n##', parameter[1], '  \n###Aggregated', '  \n')
  # subset by side
  temp_mean_list <- vector('list', length(study_sides))
  temp_sem_list <- vector('list', length(study_sides))
  temp_kin_list <- vector('list', length(study_sides))
  i=1
  for (side in study_sides){
    # subset total data by joint and axis
    temp_parameter <- paste(side[1], parameter[2], sep = ' ')
    temp_df <- split_by_joint(sorted_data, temp_parameter, parameter[3])
    # calculate means, sem, wssd, wass
    temp_means <- agg_means()
    temp_sd <- agg_sd()
    temp_assessor_means <- agg_assessor_means()
    temp_assessor_sd <- agg_assessor_sd()
    temp_mean_assessor_sd <- agg_mean_assessor_sd()
    temp_intertrial_RMS <- agg_intertrial_RMS()
    temp_mean_intertrial_RMS <- agg_mean_intertrial_RMS()
    temp_basd <- agg_basd()
    temp_ind_sem <- agg_ind_sem()
    temp_sem <- agg_sem()
    temp_wssd <- agg_wssd()
    temp_wass <- agg_wass()
    # combine
    temp_output <- agg_combine()
    # plot means, sem and kinematics *************************************************
    temp_subset <- subset(temp_output, variable != 'mean')
    temp_mean_list[[i]] <- plot_graph_means(subset(temp_subset, measurement == 'Trial mean'), parameter[1], parameter[4], parameter[5], parameter[6]) + theme(legend.position = 'none')
    leg_means <- get_legend(plot_graph_means(subset(temp_subset, measurement == 'Trial mean'), parameter[1], parameter[4], parameter[5], parameter[6]))
    temp_sem_list[[i]] <- plot_graph_sem(temp_subset) + theme(legend.position = 'none')
    leg_sem <- get_legend(plot_graph_sem(temp_subset))
    temp_kin_list[[i]] <- plot_kinematics(temp_df) + theme(legend.position = 'none')
    leg_kin <- get_legend(plot_kinematics(temp_df))
    
    #####################
    # aggregate gait reproducibility profile data
    temp_grp <- data.frame(
      'Parameter' = paste(side[1], parameter[1], sep = ' '),
      'Intertrial' = subset(temp_output, assessor == 'All' & no == 'All' & variable == 'mean' & measurement == 'Inter-trial RMS')$value,
      'WASS' = subset(temp_output, assessor == 'All' & no == 'All' & variable == 'mean' & measurement == 'Mean within assessor SD')$value,
      'BASS' = subset(temp_output, assessor == 'All' & no == 'All' & variable == 'mean' & measurement == 'Between assessor SD')$value
    )
    # loop through assessors for assessor WASS
    temp_wass_list <- vector('list', length(study_assessors))
    temp_wass_names <- vector('list', length(study_assessors))
    temp_intertrial_list <- vector('list', length(study_assessors))
    temp_intertrial_names <- vector('list', length(study_assessors))
    j=1
    for (a in study_assessors){
      temp_wass_list[[j]] <- subset(temp_output, assessor == a[1] & no == 'All' & variable == 'mean' & measurement == 'Within assessor SD')$value
      temp_intertrial_list[[j]] <- subset(temp_output, assessor == a[1] & no == 'All' & variable == 'mean' & measurement == 'Inter-trial RMS')$value
      temp_wass_names[[j]] <- paste('WASS', a[1], sep = '-')
      temp_intertrial_names[[j]] <- paste('Intertrial', a[1], sep = '-')
      j=j+1
    }
    temp_wass_df <- data.frame(temp_wass_list)
    names(temp_wass_df) <- temp_wass_names
    temp_intertrial_df <- data.frame(temp_intertrial_list)
    names(temp_intertrial_df) <- temp_intertrial_names
    # add to temp_grp
    temp_grp <- cbind(temp_grp, temp_wass_df, temp_intertrial_df)
    
    # calcualtions
    temp_grp$Procedural = sqrt(sum(temp_grp$WASS^2)+(temp_grp$BASS^2))
    temp_grp$Total = sqrt(sum(temp_grp$WASS^2) + (temp_grp$BASS^2) + (temp_grp$Intertrial^2))
    temp_grp$`Total-procedural` = temp_grp$Total - temp_grp$Procedural
    # add to list
    grp_df <- rbind(grp_df, temp_grp)
    # cleanup
    rm(temp_wass_list, temp_wass_names, temp_intertrial_list, temp_intertrial_names, temp_grp, a, j) # temp_wass_df
    
    ######################
    
    # unmelt and save df
    temp_output <- dcast(temp_output, assessor+no+measurement~variable, value.var = 'value')
    write.csv(temp_output, paste('results/', side[1], '_', parameter[1], '_df_processed.csv', sep = ''))
    # cleanup 
    rm(temp_df, temp_ind_sem, temp_means, temp_sem, temp_wass, temp_wssd, temp_assessor_means, temp_assessor_sd, temp_basd, temp_intertrial_RMS, temp_mean_intertrial_RMS, temp_sd, temp_mean_assessor_sd, temp_parameter, side, temp_output, temp_wass_df, temp_intertrial_df, temp_subset)
    i=i+1
  }
  # combine left and right plots, display graph and save
  temp_plot_means <- combine_plots2(temp_mean_list, leg_means)
  temp_plot_sem <- combine_plots2(temp_sem_list, leg_sem)
  temp_plot_kinematics <- combine_plots2(temp_kin_list, leg_kin)
  temp_plot <- plot_grid(temp_plot_means, temp_plot_sem, temp_plot_kinematics, ncol = 1)
  plot(temp_plot)
  temp_name <- paste('results/', parameter[1], '_plot_aggregated.png', sep = '')
  save_plot(temp_name, temp_plot, base_height = 15, base_width = 12)
  # clean up
  rm(parameter, temp_plot, temp_name, i)
  
  ###############
  
}
```

\newpage
## Gait reliability profile - all
  
```{r results='asis', fig.width=9, fig.height=4}
grp_long <- melt(grp_df, id.vars = 'Parameter')

g <- ggplot(subset(grp_long, variable == 'Total'), aes(x=Parameter, y=value)) + 
  geom_bar(stat='identity', position = 'identity', fill='gold') + 
  geom_bar(data = subset(grp_long, variable == 'Procedural'), aes(x=Parameter, y=value), stat='identity', position = 'identity', fill='royalblue') + 
  geom_point(data = subset(grp_long, variable == 'BASS'), aes(x=Parameter, y=value), size=12, shape=95) + 
  geom_point(data = subset(grp_long, variable == 'WASS'), aes(x=Parameter, y=value), size=12, shape=95, colour='red') +
  labs(y='SD (\u00B0)') +
  theme(axis.text.x = element_text(angle = 45, vjust=0.4, size = 12),
        axis.title.x = element_blank())
plot(g)

tab <- xtable(grp_df[c(1,2,3,4,11,12,13)])
print(tab, type = 'latex', include.rownames = FALSE, comment = FALSE)

# cleanup
rm(g, grp_df, tab)
```

  
```{r results='asis', fig.width=9, fig.height=4}
for (a in study_assessors) {
  # format pdf
  cat('\n\\pagebreak\n')
  cat('  \n## Gait reliability profile -- ', a[1], '  \n')
  # make df
  temp_intertrial <- paste('Intertrial', a[1], sep = '-')
  temp_wass <- paste('WASS', a[1], sep = '-')
  t <- data.frame(
    'Parameter' = unique(grp_long$Parameter),
    'Intertrial' = subset(grp_long, variable == temp_intertrial)$value,
    'WASS' = subset(grp_long, variable == temp_wass)$value
  )
  t$Total = sqrt((as.numeric(t$WASS)^2) + (as.numeric(t$Intertrial)^2))
  t$`Total-procedural` = as.numeric(t$Total) - as.numeric(t$WASS)
  # plot graph
  g <- plot_assessor_grp(melt(t, id.vars = 'Parameter'))
  plot(g)
  # print table
  print(xtable(t), type = 'latex', include.rownames = FALSE, comment = FALSE)
}

# cleanup
rm(a, temp_intertrial, temp_wass, t, t_long, g, grp_long)
```

