---
title: "Repeatability script"
author: "Erik Waskiewicz"
date: "01/05/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

  
```{r warning=FALSE, message=FALSE, echo=FALSE}
library('ggplot2')
library('reshape2')
library('xtable')
library('cowplot')
```

```{r echo=FALSE}
working_directory <- '/Users/erik/Projects/gait'

study_sides = list(
  c('Left', 'raw_data/Export Left 20-03-18.txt'),
  c('Right', 'raw_data/Export Right 20-03-18.txt')
)

study_participants = list(
  c('Participant 1', 'Dube_Philiani_1982-09-24_Repeatability')
)

study_assessors = list(
  c('Jav', 'JAV'),
  c('Jon', 'JON'),
  c('Lewis', 'LEWIS')
)

study_sessions = list(
  c('Session 1', '01'),
  c('Session 2', '02'),
  c('Session 3', '03'),
  c('Session 4', '04')
)

study_parameters = list(
  c('Pelvic obliquity', 'Pelvic Angles', 'Y', -6, 6, 2),
  c('Pelvic rotation', 'Pelvic Angles', 'Z', -10, 12, 5),
  c('Hip flexion', 'Hip Angles', 'X', -20, 40, 10),
  c('Hip adduction', 'Hip Angles', 'Y', -15, 10, 5),
  c('Hip rotation', 'Hip Angles', 'Z', -30, 10, 10),
  c('Knee flexion', 'Knee Angles', 'X', -15, 70, 10),
  c('Knee adduction', 'Knee Angles', 'Y', -15, 10, 5),
  c('Knee rotation', 'Knee Angles', 'Z', -22, 12, 10),
  c('Ankle dorsiflexion', 'Ankle Angles', 'X', -25, 15, 5),
  c('Ankle inversion', 'Ankle Angles', 'Y', 0, 30, 5),
  c('Foot pitch', 'Foot Pitch Angles', 'X', -80, 30, 20),
  c('Foot progression', 'Foot Pitch Angles', 'Z', -25, 25, 10)
)
```

```{r echo=FALSE}
# write functions
load_headers <- function(x) {
  df <- read.delim(file = x, header = FALSE, nrows = 5)
  df <- data.frame(t(df[, seq(2, ncol(df))]))
}

load_data <- function(x) {
  df <- read.delim(file = x, header = FALSE, skip = 5)
  df <- data.frame(t(df[, seq(2, ncol(df))]))
}
```

```{r echo=FALSE}
parse_participant <- function(x) {
  field = x[6]
  return(field)
}

parse_date <- function(x) {
  field = x[8]
  date = unlist(strsplit(field, '_'))[1]
  return(date)
}

parse_assessor <- function(x) {
  field = x[8]
  field_split = unlist(strsplit(field, '_'))[2]
  assessor = gsub('[[:digit:]]+', '', field_split)
  no = gsub(assessor, '', field_split)
  return(assessor)
}

parse_number <- function(x) {
  field = x[8]
  field_split = unlist(strsplit(field, '_'))[2]
  assessor = gsub('[[:digit:]]+', '', field_split)
  no = gsub(assessor, '', field_split)
  return(no)
}

parse_trial <- function(x) {
  field = x[9]
  field_split = unlist(strsplit(field, ' '))
  field_split = field_split[length(field_split)]
  field_split = gsub('.c3d', '', field_split)
  return(field_split)
}
```

```{r echo=FALSE}
sort_data <- function(dat, head){
  
  paths <- strsplit(toString(head$X1), ',')
  paths_split <- strsplit(unlist(paths), '\\\\')
  
  temp_df <- data.frame(
    'Participant' = sapply(paths_split, parse_participant),
    'Session assessor' = sapply(paths_split, parse_assessor),
    'Session number' = sapply(paths_split, parse_number),
    'Session date' = sapply(paths_split, parse_date),
    'Trial' = sapply(paths_split, parse_trial),
    'Joint' = head$X2,
    'Plane' = head$X5
    )
  temp_df$unique_id <- make.names(paste(temp_df$Session.assessor, temp_df$Session.number, temp_df$Joint, temp_df$Plane, temp_df$Trial, sep='_'), unique = TRUE)
  
  #replace names in columns with nicely formatted names
  for (participant in study_participants) {
    temp_df$Participant <- sapply(temp_df$Participant, function(x) gsub(participant[2], participant[1], x))
  }
  for (assessor in study_assessors) {
    temp_df$Session.assessor <- sapply(temp_df$Session.assessor, function(x) gsub(assessor[2], assessor[1], x))
  }
  for (session in study_sessions) {
    temp_df$Session.number <- sapply(temp_df$Session.number, function(x) gsub(session[2], session[1], x))
  }
  
  sorted_data <- cbind(temp_df, dat)
  remove_df <- subset(sorted_data, (Trial=='Static' | Joint=='Right Ankle Angles' & Plane=='Z') | (Joint=='Right Foot Pitch Angles' & Plane=='Y') | Joint=='Right Ankle Angles_CGM' | Joint=='Right Foot Progression' | Joint=='Left Ankle Angles' & Plane=='Z' | (Joint=='Left Foot Pitch Angles' & Plane=='Y') | Joint=='Left Ankle Angles_CGM' | Joint=='Left Foot Progression')
  sorted_data <- sorted_data[setdiff(rownames(sorted_data), rownames(remove_df)),]
  
  return(sorted_data)
}
```

```{r echo=FALSE}
split_by_joint <- function(dat, x,y) {
  df <- subset(dat, Joint == x & Plane == y)
  df <- df[setdiff(colnames(df), c('Participant', 'Session.date', 'Trial', 'Joint', 'Plane'))]
  df <- melt(df, id.vars = c('Session.assessor', 'Session.number', 'unique_id'))
}
```

```{r echo=FALSE}
# inputs - data split by day, y label, day label, (y axis limits?)
plot_graph_all <- function(x, t, l, ylower, yupper, increments) {
  plot <- ggplot(x, aes(x=as.numeric(variable)-1, y=value, group=unique_id, colour=Session.assessor)) +
  geom_line() +
  labs(title=t, x='Gait cycle (%)', y=paste(l, ' (degrees)')) +
  geom_hline(yintercept = 0) +
  scale_y_continuous(expand = c(0, 0), limits = c(as.numeric(ylower), as.numeric(yupper)), breaks = c(seq(-360, 360, as.numeric(increments)))) + 
  scale_x_continuous(expand = c(0, 0), limits = c(0, 101), breaks = c(seq(0, 100, 20))) + 
  theme(panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      axis.line = element_line(),
      legend.position = 'bottom'
      )
}
```

```{r echo=FALSE}
combine_plots <- function(x, leg) {
  plot_left <- plot_grid(plotlist = x[[1]], ncol = 1)
  plot_right <- plot_grid(plotlist = x[[2]], ncol = 1)
  plot_combined <- plot_grid(plot_left, plot_right, ncol = 2)
  plot <- plot_grid(plot_combined, leg, ncol = 1, rel_heights = c(20, 1))
  # save plot
  #save_plot(name, plot, base_height = 15, base_width = 12)
}
```
  
```{r echo=FALSE}
# inputs - mean data for all sessions and assessors, y label, (title + y axid limits?)
plot_graph_means <- function(x,l, ylower, yupper, increments) {
  plot <- ggplot(x, aes(x=as.numeric(variable)-1, y=value, group=unique_id, colour=assessor, linetype=no)) +
    geom_line() +
    labs(x='Gait cycle (%)', y=paste(l, ' (degrees)')) +
    geom_hline(yintercept = 0) +
    scale_y_continuous(expand = c(0, 0), limits = c(as.numeric(ylower), as.numeric(yupper)), breaks = c(seq(-360, 360, as.numeric(increments)))) + 
    scale_x_continuous(expand = c(0, 0), limits = c(0, 101), breaks = c(seq(0, 100, 20))) + 
    theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(),
        legend.position = 'bottom'
        )
}
```

```{r echo=FALSE}
# inputs - mean data for all sessions and assessors, y label, (title + y axid limits?)
plot_graph_sem <- function(x) {
  plot <- ggplot(subset(x, measurement == 'SEM'), aes(x=as.numeric(variable)-1, y=value, group=unique_id, colour=assessor, linetype=no)) +
    geom_line() +
    labs(x='Gait cycle (%)', y=paste('SEM (degrees)')) +
    geom_line(data = subset(x, measurement == 'WSSD'), colour = 'black') +
    scale_y_continuous(expand = c(0, 0)) +
    scale_x_continuous(expand = c(0, 0), limits = c(0, 101), breaks = c(seq(0, 100, 20))) + 
    theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(),
        legend.position = 'bottom'
        )
}
```

```{r echo=FALSE}
plot_kinematics <- function(x) {
  df <- subset(x, variable == 'mean')
  trial_mean <- mean(df$value)
  df$dev <- lapply(df$value, function(x){x - trial_mean})
  temp_plot <- ggplot(df, aes(x=unique_id, y=value, group=Session.assessor, colour=Session.number)) + 
    geom_point() +
    geom_hline(yintercept = trial_mean, colour = '#999999') +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          legend.position = 'bottom') +
    facet_grid(. ~ Session.assessor, scales = 'free')
}
```

```{r echo=FALSE}
# calculate means per session+assessor - mean at each percentile of all the trials each assessor has done in a session
agg_means <- function() {
  temp_means <- dcast(temp_df, Session.assessor+Session.number~variable, mean)
  temp_means$measurement <- rep('Trial mean', nrow(temp_means))
  temp_means <- melt(temp_means, id.vars = c('Session.number', 'Session.assessor', 'measurement'))
}
# aggregate sd
agg_sd <- function() {
  temp_sd <- dcast(temp_df, Session.assessor+Session.number~variable, sd)
  temp_sd$measurement <- rep('Trial SD', nrow(temp_sd))
  temp_sd <- melt(temp_sd, id.vars = c('Session.number', 'Session.assessor', 'measurement'))
}
  
# means per participant - 
agg_assessor_means <- function() {
  temp_assessor_means <- data.frame(
    'Session.number' = rep('All', length(study_assessors)),
    'measurement' = rep('Trial mean', length(study_assessors))
    )
  temp_assessor_means <- cbind(temp_assessor_means, dcast(temp_means, Session.assessor ~ variable, mean))
  temp_assessor_means <- melt(temp_assessor_means, id.vars = c('Session.number', 'Session.assessor', 'measurement'))
}

# sd per participant - within assessor SD
agg_assessor_sd <- function() {
  temp_assessor_sd <- data.frame(
    'Session.number' = rep('All', length(study_assessors)),
    'measurement' = rep('Within assessor SD', length(study_assessors))
    )
  temp_assessor_sd <- cbind(temp_assessor_sd, dcast(temp_means, Session.assessor ~ variable, sd))
  temp_assessor_sd <- melt(temp_assessor_sd, id.vars = c('Session.number', 'Session.assessor', 'measurement'))
}

# mean within assessor SD
agg_mean_assessor_sd <- function() {
  temp_subset <- subset(temp_assessor_sd, variable == 'mean')
  temp_df <- data.frame(
    'Session.number' = 'All',
    'Session.assessor' = 'All',
    'measurement' = 'Mean within assessor SD'
    )
  temp_df <- cbind(temp_df, dcast(temp_subset, Session.number ~ variable, function(x) {sqrt(sum(x^2) / length(x))}))
  temp_df <- melt(temp_df, id.vars = c('Session.number', 'Session.assessor', 'measurement'))
}

# Between assessor SD
agg_basd <- function() {
  temp_basd <- data.frame(
    'Session.number' = rep('All', length(unique(temp_means$variable))),
    'Session.assessor' = rep('All', length(unique(temp_means$variable))),
    'measurement' = rep('Between assessor SD', length(unique(temp_means$variable)))
    )
  temp_basd <- cbind(temp_basd, aggregate(value~variable, data = temp_assessor_means, FUN = sd))
}

# inter-trial rms - per assessor
agg_intertrial_RMS <- function() {
  temp_df <- data.frame(
    'Session.number' = rep('All', length(study_assessors)),
    'measurement' = rep('Inter-trial RMS', length(study_assessors))
    )
  temp_df <- cbind(temp_df, dcast(temp_sd, Session.assessor ~ variable, function(x) {sqrt(sum(x^2) / length(x))}))
  temp_df <- melt(temp_df, id.vars = c('Session.number', 'Session.assessor', 'measurement'))
}

# intertrial rms - mean
agg_mean_intertrial_RMS <- function() {
  temp_subset <- subset(temp_sd, variable == 'mean')
  temp_df <- data.frame(
    'Session.number' = 'All',
    'Session.assessor' = 'All',
    'measurement' = 'Inter-trial RMS'
    )
  temp_df <- cbind(temp_df, aggregate(value~variable, data = temp_subset, function(x) {sqrt(sum(x^2) / length(x))}))
}

# individual sem - for each participant - 
agg_ind_sem <- function() {
  temp_ind_sem <- data.frame(
    'Session.number' = rep('All', length(study_assessors)),
    'measurement' = rep('Individual_SEM', length(study_assessors))
    )
  temp_ind_sem <- cbind(temp_ind_sem, dcast(temp_means, Session.assessor ~ variable, sd))
  temp_ind_sem <- melt(temp_ind_sem, id.vars = c('Session.number', 'Session.assessor', 'measurement'))
}
  
# sem
agg_sem <- function() {
  temp_sem <- data.frame(
    'Session.number' = temp_ind_sem$Session.number,
    'Session.assessor' = temp_ind_sem$Session.assessor,
    'measurement' = rep('SEM', nrow(temp_ind_sem)),
    'variable' = temp_ind_sem$variable,
    'value' = sapply(temp_ind_sem$value, function(x) {sqrt(sum(x^2) / length(study_participants))})
  )
}
  
# wssd
agg_wssd <- function() {
  temp_wssd <- data.frame(
    'Session.number' = rep('All', length(unique(temp_means$variable))),
    'Session.assessor' = rep('All', length(unique(temp_means$variable))),
    'measurement' = rep('WSSD', length(unique(temp_means$variable)))
    )
  temp_wssd <- cbind(temp_wssd, aggregate(value~variable, data = temp_means, FUN = sd))
}
  
# wass
agg_wass <- function() {
  temp_wass <- data.frame(
    'Session.number' = rep('All', length(unique(temp_means$variable))),
    'Session.assessor' = rep('All', length(unique(temp_means$variable))),
    'measurement' = rep('WASS', length(unique(temp_means$variable)))
    )
  temp_wass <- cbind(temp_wass, aggregate(value~variable, data = temp_ind_sem, FUN = function(x) {sqrt(sum(x^2) / length(study_participants))}))
}

agg_combine <- function() {
    names(temp_means) <- c('no', 'assessor', 'measurement', 'variable', 'value')
    names(temp_sd) <- c('no', 'assessor', 'measurement', 'variable', 'value')
    names(temp_assessor_means) <- c('no', 'assessor', 'measurement', 'variable', 'value')
    names(temp_assessor_sd) <- c('no', 'assessor', 'measurement', 'variable', 'value')
    names(temp_mean_assessor_sd) <- c('no', 'assessor', 'measurement', 'variable', 'value')
    names(temp_intertrial_RMS) <- c('no', 'assessor', 'measurement', 'variable', 'value')
    names(temp_mean_intertrial_RMS) <- c('no', 'assessor', 'measurement', 'variable', 'value')
    names(temp_basd) <- c('no', 'assessor', 'measurement', 'variable', 'value')
    names(temp_ind_sem) <- c('no', 'assessor', 'measurement', 'variable', 'value')
    names(temp_sem) <- c('no', 'assessor', 'measurement', 'variable', 'value')
    names(temp_wssd) <- c('no', 'assessor', 'measurement', 'variable', 'value')
    names(temp_wass) <- c('no', 'assessor', 'measurement', 'variable', 'value')
    df <- rbind(temp_means, temp_sd, temp_assessor_means, temp_assessor_sd, temp_mean_assessor_sd, temp_intertrial_RMS, temp_mean_intertrial_RMS, temp_basd, temp_ind_sem, temp_sem, temp_wssd, temp_wass)
    df$unique_id <- make.names(paste(df$assessor, df$no, df$measurement, sep='_'))
    
    return(df)
}
```







```{r warning=FALSE, echo=FALSE}
setwd(working_directory)
dir.create('results')
```

# Parameters
```{r echo=FALSE, results='asis'}
for (parameter in study_parameters) {
  cat('  \n*', parameter[1], '  \n')
}
```
\newpage

```{r echo=FALSE}
input_list <- vector('list', length(study_sides))
i=1
for (data in study_sides) {
  # load headers and data seperately
  temp_headers <- load_headers(data[2])
  temp_data <- load_data(data[2])
  temp_data$mean <- rowMeans(temp_data)
  # combine and sort data
  temp_sorted <- sort_data(temp_data, temp_headers)
  input_list[[i]] <- temp_sorted
  i=i+1
}
# concatenate dataframes in list
sorted_data <- do.call('rbind', input_list)
write.csv(sorted_data, 'results/all_data_sorted.csv')
# clean up
rm(temp_headers, temp_data, temp_sorted, data, input_list, i)
```

Create empty df for aggregated gait reliability profile data
```{r echo=FALSE}
  # create gait reliability profile df
  grp_df <- data.frame('Parameter' = character(),
                   'Inter-trial' = character(), 
                   'WASS' = character(),
                   'BASS' = character(),
                   'Procedural' = character(),
                   'Total' = character(),
                   'Total-procedural' = character()
                   )
```

# FIX - Only saving roght side!
```{r results='asis', message=FALSE, fig.width=9, fig.height=12, echo=FALSE}
for (parameter in study_parameters){
  # format pdf
  cat('\n\\pagebreak\n')
  cat('  \n##', parameter[1], '  \n###All trials', '  \n')
  # subset by side
  temp_side_list <- vector('list', length(study_sides))
  i=1
  for (side in study_sides){
    temp_parameter <- paste(side[1], parameter[2], sep = ' ')
    # subset total data by joint and axis
    temp_df <- split_by_joint(sorted_data, temp_parameter, parameter[3])
    temp_output <- dcast(temp_df, Session.assessor+Session.number+unique_id~variable, value.var = 'value')
    write.csv(temp_output, paste('results/', side[1], '_', parameter[1], '_df_all.csv', sep = ''))
    # Loop through sessions
    temp_session_list <- vector('list', length(study_sessions))
    j=1
    for (study in study_sessions) {
      # subset data
      temp_subset <- subset(temp_df, Session.number == study[1])
      # plot graph
      temp_plot <- plot_graph_all(temp_subset, paste(study[1], side[1], sep = ' - '), parameter[1], parameter[4], parameter[5], parameter[6])
      temp_leg <- get_legend(temp_plot)
      temp_plot <- temp_plot + theme(legend.position = 'none')
      temp_session_list[[j]] <- temp_plot
      # clean up
      rm(temp_subset, temp_plot)
      j=j+1
    }
    temp_side_list[[i]] <- temp_session_list
    rm(study, j)
    i=i+1
  }
  rm(side, i)
  # combine left and right plots, display plot and save
  temp_plot <- combine_plots(temp_side_list, temp_leg)
  plot(temp_plot)
  temp_name <- paste('results/', parameter[1], '_plot_all.png', sep = '')
  save_plot(temp_name, temp_plot, base_height = 15, base_width = 12)
  # clean up
  rm(temp_df, temp_plot, temp_session_list, temp_side_list, temp_parameter, temp_leg, temp_name)

################
  
  # format pdf
  cat('\n\\pagebreak\n')
  cat('  \n##', parameter[1], '  \n###Aggregated', '  \n')
  # subset by side
  temp_side_list <- vector('list', length(study_sides))
  i=1
  for (side in study_sides){
    # subset total data by joint and axis
    temp_parameter <- paste(side[1], parameter[2], sep = ' ')
    temp_df <- split_by_joint(sorted_data, temp_parameter, parameter[3])
    # calculate means, sem, wssd, wass
    temp_means <- agg_means()
    temp_sd <- agg_sd()
    temp_assessor_means <- agg_assessor_means()
    temp_assessor_sd <- agg_assessor_sd()
    temp_mean_assessor_sd <- agg_mean_assessor_sd()
    temp_intertrial_RMS <- agg_intertrial_RMS()
    temp_mean_intertrial_RMS <- agg_mean_intertrial_RMS()
    temp_basd <- agg_basd()
    temp_ind_sem <- agg_ind_sem()
    temp_sem <- agg_sem()
    temp_wssd <- agg_wssd()
    temp_wass <- agg_wass()
    # combine
    temp_output <- agg_combine()
    # plot means, sem and kinematics
    temp_plot_means <- plot_graph_means(subset(temp_output, measurement == 'Trial mean'), parameter[1], parameter[4], parameter[5], parameter[6])
    temp_plot_sem <- plot_graph_sem(temp_output)
    temp_plot_kinematics <- plot_kinematics(temp_df)
    # combine plots
    temp_side_list[[i]] <- plot_grid(temp_plot_means, temp_plot_sem, temp_plot_kinematics, ncol = 1)
    
    #####################
    
    temp_grp <- data.frame(
      'Parameter' = paste(side[1], parameter[1], sep = ' '),
      'Inter-trial' = subset(temp_output, assessor == 'All' & no == 'All' & variable == 'mean' & measurement == 'Inter-trial RMS')$value,
      'WASS' = subset(temp_output, assessor == 'All' & no == 'All' & variable == 'mean' & measurement == 'Mean within assessor SD')$value,
      'BASS' = subset(temp_output, assessor == 'All' & no == 'All' & variable == 'mean' & measurement == 'Between assessor SD')$value
    )
    
    temp_list <- vector('list', length(study_assessors))
    temp_names <- vector('list', length(study_assessors))
    j=1
    for (a in study_assessors){
      temp_value <- subset(temp_output, assessor == a[1] & no == 'All' & variable == 'mean' & measurement == 'Within assessor SD')$value
      temp_list[[j]] <- c(temp_value)
      temp_names[[j]] <- paste('WASS', a[1], sep = '-')
      j=j+1
    }
    df <- data.frame(temp_list)
    names(df) <- temp_names
    # ADD TO MAIN DF
    
    temp_grp$Procedural = sqrt(sum(temp_grp$WASS^2)+(temp_grp$BASS^2))
    temp_grp$Total = sqrt(sum(temp_grp$WASS^2) + (temp_grp$BASS^2) + (temp_grp$Inter.trial^2))
    temp_grp$`Total-procedural` = sum(temp_grp$Total - temp_grp$Procedural)
    grp_df <- rbind(grp_df, temp_grp)
    
    ######################
    
    # unmelt and save df
    #temp_output <- dcast(temp_output, assessor+no+measurement~variable, value.var = 'value')
    #write.csv(temp_output, paste('results/', side[1], '_', parameter[1], '_df_processed.csv', sep = ''))
    # cleanup 
    rm(temp_df, temp_ind_sem, temp_means, temp_sem, temp_wass, temp_wssd, temp_assessor_means, temp_assessor_sd, temp_basd, temp_intertrial_RMS, temp_mean_intertrial_RMS, temp_sd, temp_mean_assessor_sd, temp_parameter, temp_plot_means, temp_plot_sem, temp_plot_kinematics, temp_grp, side)
    i=i+1
  }
  # combine left and right plots, display graph and save
  temp_plot <- plot_grid(plotlist = temp_side_list, ncol = 2)
  plot(temp_plot)
  temp_name <- paste('results/', parameter[1], '_plot_aggregated.png', sep = '')
  save_plot(temp_name, temp_plot, base_height = 15, base_width = 12)
  # clean up
  rm(parameter, temp_plot, temp_side_list, temp_name, i)
  
  ###############
  
}
```

## Gait reliability profile
  
```{r results='asis', message=FALSE, fig.width=9, fig.height=5, echo=FALSE}
grp_long <- melt(grp_df, id.vars = c('Parameter'))

g <- ggplot(subset(grp_long, variable == 'Total'), aes(x=Parameter, y=value)) + 
  geom_bar(stat='identity', position = 'identity', fill='orange') + 
  geom_bar(data = subset(grp_long, variable == 'Procedural'), aes(x=Parameter, y=value), stat='identity', position = 'identity', fill='blue') + 
  geom_point(data = subset(grp_long, variable == 'BASS'), aes(x=Parameter, y=value), size=8, shape=95) + 
  geom_point(data = subset(grp_long, variable == 'WASS'), aes(x=Parameter, y=value), size=8, shape=95, colour='red') +
  theme(axis.text.x = element_text(angle = 45, vjust=0.4, size = 12))
g

tab <- xtable(grp_df)
print(tab, type = 'latex')
```



